// Generated by tools/generate_recursive_industry_universal_source.py.
namespace RecursiveIndustry;

internal static partial class RecursiveIndustryIcons
{
    public const string ComminutionHub = Root + "comminution_hub.png";
    public const string MineralProductsWorks = Root + "mineral_products_works.png";
    public const string PrimarySmelter = Root + "primary_smelter.png";
    public const string PrecisionMetalsWorks = Root + "precision_metals_works.png";
    public const string RefineryComplex = Root + "refinery_complex.png";
    public const string GasFertilizerComplex = Root + "gas_fertilizer_complex.png";
    public const string MaterialsChemistryComplex = Root + "materials_chemistry_complex.png";
    public const string MedicalChemistryComplex = Root + "medical_chemistry_complex.png";
    public const string FoodProcessingCampus = Root + "food_processing_campus.png";
    public const string FoodPackCampus = Root + "food_pack_campus.png";
    public const string CropSoilBioprocessing = Root + "crop_soil_bioprocessing.png";
    public const string BioenergyCenter = Root + "bioenergy_center.png";
    public const string WaterUtility = Root + "water_utility.png";
    public const string ThermalEmissionsUtility = Root + "thermal_emissions_utility.png";
    public const string MaterialsRecoveryCenter = Root + "materials_recovery_center.png";
    public const string NuclearFuelComplex = Root + "nuclear_fuel_complex.png";
    public const string PrecisionComponentsFab = Root + "precision_components_fab.png";
    public const string GeneralManufacturingFab = Root + "general_manufacturing_fab.png";
    public const string OrbitalFabricationFab = Root + "orbital_fabrication_fab.png";
}
